version: '3.8'

services:
  db:
    ports:
      - 5432:5432
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - my_network

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build: ./astro
    ports:
      - 4321:4321
    volumes:
      - ./astro:/usr/src/app  # Useful for development
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network
