version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  frontend:
    build: ./astro
    ports:
      - 4321:4321
    volumes:
      - ./astro:/usr/src/app  # Useful for development
    depends_on:
      - web
    networks:
      - default

  redoc:
    image: redocly/redoc
    container_name: redoc
    volumes:
      - ./app/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    environment:
      SPEC_URL: /api-docs/openapi.yaml
    expose:
      - "80"

volumes:
  postgres_data:
  static_volume:
  media_volume: