# Generated by Django 5.1.3 on 2025-01-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MagazineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('issue_number', models.IntegerField()),
                ('front_cover', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='MagazineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_year', models.DateField()),
                ('articles', models.ManyToManyField(through='catalog.AuthorArticle', to='catalog.author')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.magazineissue')),
            ],
        ),
        migrations.AddField(
            model_name='authorarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.magazinearticle'),
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(through='catalog.AuthorArticle', to='catalog.magazinearticle'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.magazinearticle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tag')),
            ],
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='tags',
            field=models.ManyToManyField(through='catalog.ArticleTag', to='catalog.tag'),
        ),
    ]
